#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/6269405p/work ensure=absent force=true
puppet resource file /tmp/6269405p/work ensure=directory
cd /tmp/6269405p/work 
git clone https://github.com/RP23003387/POC_REPO.git
cp -p /tmp/6269405p/work/POC_REPO/6269405p_index.html /var/www/html/index.html
